### ISSUE TITLE
Thập - Assessment #16

### ISSUE THREAD

**Issue by longhypepoly** [hypepoly-internship-2022/thi-thap-assessment-16#1]

**Comment by longhypepoly** [comment]
Đặt tên class nên có ý nghĩa cụ thể, chứ ko nên đặt tên theo kiểu như `Btn1`. Ví dụ em handle movement của Object, thì em nên đặt tên là Movement. Tương tự khi đặt tên function cũng như thế nhé 😉 
Good job 👍

**Comment by Dangthap** [comment]
dạ anh


Vào Th 5, 12 thg 1, 2023 vào lúc 14:23 Long Tran ***@***.***>
đã viết:
